# Generated by Django 4.2.5 on 2023-09-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrasa_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('eiin', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('madrasa_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLink1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_website', models.CharField(max_length=150)),
                ('link_of_site', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLink2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_website', models.CharField(max_length=150)),
                ('link_of_site', models.CharField(max_length=5000)),
            ],
        ),
    ]
