# Generated by Django 4.2.5 on 2023-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addclass_notice_syllabus_examresult_classroutine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='add_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='ClassRoutine/'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='add_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='ExamResult/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='add_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='Notice/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='total_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='add_file',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='Syllabus/'),
        ),
    ]
