# Generated by Django 4.2.5 on 2023-09-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_classroutine_add_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('add_photo', models.ImageField(upload_to='Gallary/')),
            ],
        ),
        migrations.CreateModel(
            name='Lagacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_of_top_person', models.CharField(max_length=150)),
                ('name_of_top_person', models.CharField(max_length=350)),
                ('person_speach', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='Lagacy/')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=90)),
                ('select_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.addclass')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('photo', models.ImageField(upload_to='Teacher/')),
                ('present_address', models.CharField(blank=True, max_length=350, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=350, null=True)),
                ('rank', models.CharField(max_length=150)),
                ('year_of_experience', models.IntegerField(blank=True, null=True)),
                ('subject_teach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
        ),
    ]
