# Generated by Django 4.2.5 on 2023-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teacher_mobile_teacher_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('e_id', models.IntegerField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='Teacher/')),
                ('present_address', models.CharField(blank=True, max_length=350, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=350, null=True)),
                ('rank', models.CharField(max_length=150)),
            ],
        ),
    ]
