# Generated by Django 4.2.5 on 2023-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagacy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lagacy',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
