# Generated by Django 4.2.5 on 2023-09-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_lagacy_email_lagacy_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=150)),
                ('add_photo', models.ImageField(upload_to='slider/')),
                ('details_of_photo', models.TextField()),
            ],
        ),
    ]
